@extends('layouts.app')
@section('title','Manajemen User')
@section('page_title','Manajemen User')
@section('content')
@php
$sortLink=function($column,$label) use($sort,$dir){$next=($sort===$column&&$dir==='asc')?'desc':'asc';$icon=$sort===$column?($dir==='asc'?'bi-sort-up':'bi-sort-down'):'bi-arrow-down-up';return '<a class="text-decoration-none text-muted" href="'.request()->fullUrlWithQuery(['sort'=>$column,'dir'=>$next]).'">'.$label.' <i class="bi '.$icon.'"></i></a>';};
@endphp
<div class="page-hdr"><div class="page-hdr-left"><h1><i class="bi bi-person-gear me-2" style="color:var(--primary)"></i>Manajemen User</h1><nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item active">Auto logout setelah {{ env('AUTH_TIMEOUT', 15) }} menit tidak aktif</li></ol></nav></div><a href="{{ route('users.create') }}" class="btn btn-primary px-4"><i class="bi bi-person-plus me-2"></i>Tambah User</a></div>
<div class="card mb-3"><div class="card-body"><form method="GET" class="row g-2 align-items-end"><div class="col-md-4"><input type="text" name="search" class="form-control" placeholder="Cari nama/username/email..." value="{{ request('search') }}"></div><div class="col-md-2"><select name="role" class="form-select"><option value="">Semua Role</option>@foreach($roles as $value=>$label)<option value="{{ $value }}" {{ request('role')===$value?'selected':'' }}>{{ $label }}</option>@endforeach</select></div><div class="col-md-2"><select name="status" class="form-select"><option value="">Semua Status</option><option value="active" {{ request('status')==='active'?'selected':'' }}>Aktif</option><option value="inactive" {{ request('status')==='inactive'?'selected':'' }}>Nonaktif</option></select></div><div class="col-md-2"><select name="per_page" class="form-select">@foreach([10,15,20,50,100] as $n)<option value="{{ $n }}" {{ request('per_page',15)==$n?'selected':'' }}>{{ $n }} row</option>@endforeach</select></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-primary"><i class="bi bi-search me-1"></i>Cari</button><a href="{{ route('users.index') }}" class="btn btn-outline-secondary"><i class="bi bi-x"></i></a></div></form></div></div>
<div class="card"><div class="card-header"><h6 class="mb-0">Daftar Pengguna Sistem <span class="badge bg-success ms-1">{{ $users->total() }}</span></h6></div><div class="table-wrapper"><table class="table mb-0"><thead><tr><th>#</th><th>{!! $sortLink('name','Nama') !!}</th><th>{!! $sortLink('username','Username') !!}</th><th>{!! $sortLink('email','Email') !!}</th><th>{!! $sortLink('role','Role') !!}</th><th>Password</th><th>{!! $sortLink('is_active','Status Akun') !!}</th><th>{!! $sortLink('last_seen_at','Online/Offline') !!}</th><th>{!! $sortLink('created_at','Dibuat') !!}</th><th style="width:100px">Aksi</th></tr></thead><tbody>
@forelse($users as $i=>$u)<tr><td class="text-muted small">{{ $users->firstItem()+$i }}</td><td><strong>{{ $u->name }}</strong>@if($u->id===auth()->id()) <span class="badge bg-success">Anda</span>@endif</td><td><span style="font-family:monospace;background:#f3f4f6;padding:2px 8px;border-radius:5px">{{ $u->username }}</span></td><td class="text-muted">{{ $u->email ?? '-' }}</td><td><span class="badge bg-{{ $u->role==='pemilik'?'warning':($u->role==='admin'?'primary':'secondary') }}">{{ $u->role_label }}</span></td><td>@if($u->visible_password)<div class="input-group input-group-sm" style="min-width:150px"><input type="password" class="form-control form-control-sm" value="{{ $u->visible_password }}" readonly><button class="btn btn-outline-secondary" type="button" onclick="const i=this.previousElementSibling;i.type=i.type==='password'?'text':'password';this.innerHTML=i.type==='password'?'👁':'🙈';">👁</button></div>@else<span class="text-muted small">Password lama tidak tersedia; reset dulu</span>@endif</td><td>@if($u->is_active)<span class="badge bg-success">Aktif</span>@else<span class="badge bg-danger">Nonaktif</span>@endif</td><td>@if($u->is_online)<span class="badge bg-success">Online</span>@else<span class="badge bg-secondary">Offline</span>@endif<div class="small text-muted">{{ $u->last_seen_at ? $u->last_seen_at->diffForHumans() : '-' }}</div></td><td class="text-muted small">{{ $u->created_at->format('d/m/Y') }}</td><td><div class="d-flex gap-1"><a href="{{ route('users.edit',$u) }}" class="btn btn-sm btn-icon btn-outline-primary"><i class="bi bi-pencil"></i></a>@if($u->id!==auth()->id() && $u->role!=='pemilik')<form method="POST" action="{{ route('users.destroy',$u) }}" onsubmit="return confirm('Hapus user {{ $u->name }}?')">@csrf @method('DELETE')<button class="btn btn-sm btn-icon btn-outline-danger"><i class="bi bi-trash"></i></button></form>@endif</div></td></tr>@empty<tr><td colspan="10" class="text-center py-5 text-muted">Belum ada pengguna</td></tr>@endforelse
</tbody></table></div>@if($users->hasPages())<div class="card-body border-top">{{ $users->withQueryString()->links() }}</div>@endif</div>
@endsection
